backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"  # Where uploaded images are stored
public_folder: "/images/uploads"  # Public URL for uploaded images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"  # Location of home page content
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }